// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jehcdnqiqtponkybifla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplaGNkbnFpcXRwb25reWJpZmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MTMxNzYsImV4cCI6MjA3NDE4OTE3Nn0.nb0PL5cv3QAqQU2Je4mzdYqkNetwvRAZ1bloQDva_jY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});